exp:
    exp_name: cond_diff_debug
    ckpt_dir: ./MLP
    ckpt_freq: 20
    device: auto
    accelerator: auto
    data_dir:  /home/ahmad/ahmad_experiments/retinal_data/Dataset_SPIE
    pickle_dir: /home/ahmad/ahmad_experiments/pickle_files_spie
    image_extension: png
    num_workers: 23
    model_ckpt_path: /home/ahmad/ahmad_experiments/retinal_cond_diff/checkpoints/epoch=94-step=81890.ckpt
    sample_image_dir: Sampled_images/Cond_Diff_pretrained_sample_epoch_94_1000_clipped
    log_every_n_steps: 10
    save_top_k: 20
    denoised_img_dir: encode_denoised_DDIM_DDIM_intermediates_800
    logdir: logs/cond_diff_debug
    csv_dir: scores
    training_type: cond_diff_continue

hparams:
    restore_ckpt:
    seed: 0
    batch_size: 6
    min_epochs: 1
    max_epochs: 2
    num_sanity_val_steps: 1
    number_of_samples: 20
    num_classes: 6

    DiffusionModelUnet:
        spatial_dims : 2
        in_channels : 3
        out_channels : 3
        num_res_blocks: [2,2,2,2,2,2]
        num_channels : [256, 256, 512, 512, 1024, 1024]
        attention_levels : [False, False, False, True, True, True]
        norm_num_groups: 32
        resblock_updown: True
        num_head_channels: [64, 64, 64, 64, 64, 64]
        with_conditioning: False
        transformer_num_layers: 1
        num_class_embeds: 6
        upcast_attention: False
        use_flash_attention: False

    mlp:
        layer_1: 512
        num_classes: 6

    pretrained_scheduler_type: conditional_DDPM
    scheduler_type: DDPM
    DDPMScheduler: 
        num_train_timesteps: 1000
        schedule: linear_beta
        variance_type: fixed_small
        clip_sample: True
        prediction_type: epsilon
    
    DDIMScheduler: 
        num_train_timesteps: 1000
        schedule: linear_beta
        clip_sample: True
        prediction_type: epsilon
        set_alpha_to_one: True
    
    
    num_train_timesteps: 1000
    num_inference_timesteps: 1000
    validation_sample_inspect_epoch: 5
    runs: 10

    image_h: 224
    image_w: 224 

    learning_rate: 0.0001
    denoising_timestep: 800