exp:
    exp_name: Cond_Diff_Retinal_18k
    ckpt_dir: ./Cond_Diff
    ckpt_freq: 20
    device: auto
    accelerator: auto 
    data_dir:  /work/wilms_lab/ahmad/Dataset_SPIE
    image_extension: png
    num_workers: 1
    model_ckpt_path: /home/ahmad.omarahsan/retinal_cond_diff/epoch=161-step=82134.ckpt
    sample_image_dir: 161_epoch_samples
    log_every_n_steps: 10
    save_top_k: 20
    denoised_img_dir: encode_denoised_DDIM_DDIM_intermediates_800
    logdir: logs/Cond_Diff_Tests


hparams:
    restore_ckpt:
    seed: 0
    batch_size: 8
    min_epochs: 1
    max_epochs: 1
    num_sanity_val_steps: 1
    number_of_samples: 20

    DiffusionModelUnet:
        spatial_dims : 2
        in_channels : 3
        out_channels : 3
        num_res_blocks: [2,2,2,2,2,2]
        num_channels : [256, 256, 512, 512, 1024, 1024]
        attention_levels : [False, False, False, True, True, True]
        norm_num_groups: 32
        resblock_updown: True
        num_head_channels: [64, 64, 64, 64, 64, 64]
        with_conditioning: False
        transformer_num_layers: 1
        num_class_embeds: 6
        upcast_attention: False
        use_flash_attention: False

    pretrained_scheduler_type: conditional_DDPM
    scheduler_type: DDPM
    DDPMScheduler: 
        num_train_timesteps: 1000
        schedule: linear_beta
        variance_type: fixed_small
        clip_sample: True
        prediction_type: epsilon
    
    DDIMScheduler: 
        num_train_timesteps: 1000
        schedule: linear_beta
        variance_type: fixed_small
        clip_sample: True
        prediction_type: epsilon
        set_alpha_to_one: True
    
    
    num_train_timesteps: 1000
    num_inference_timesteps: 1000

    image_h: 224
    image_w: 224 

    learning_rate: 0.00001
    denoising_timestep: 800